Protocol update
Wolkabout/WolkConnect-Python pull request #66
Opened 2021-09-08 14:23 UTC by djesic

An overview of changes:

WolkConnect
- `WolkConnect ` no longer takes functions for actuators and configurations, but a function for incoming feed values that can be set when creating the `WolkConnect` object with `.with_incoming_feed_value_handler`
-  `.with_file_management` : `max_file_size` argument removed
- `WolkConnect.connect()` now gathers device parameters from publishes them on connect
- `add_feed_value` introduced. It can handle single or multiple readings.
- Introduced `pull_parameters` and `pull_feed_values` for devices with PULL data delivery method.
- Introduced `register_feed` and `remove_feed`
- Introduced `register_attribute`

Protocol has been updated, see `wolkabout_protocol_message_factory` & `wolkabout_protocol_message_deserializer` for details.

File Management:
- Updated what information the `file_list` message contains

Firmware Update:
- Firmware update outcome message is created and published when connecting to the platform, instead of on module creation.

MQTT connectivity:
- Introduced a retry for reconnection

TODO:
Update readme for new APIs
Update examples to reflect new functionality 

NOTE:
Should not be merged into master when approved!!

2021-09-10 10:16 UTC, srdjastankovic commented
are manifest files still relevant on the platform side? eg: simple_example.json

2021-09-10 10:19 UTC, srdjastankovic commented
update 
`docs/source/WolkConnect-Functional-Docu.md`

2021-09-10 13:32 UTC, srdjastankovic requested changes

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/model/unit.py
> +"""Enumeration of available units on the Platform."""
Can we this file generate from platform and implement import mehanism for connectors? Beacuse it will chnage during time and instance.

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/mqtt_connectivity_service.py
> +            while retries < 3:
Make it confirgurable

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/wolk_connect.py
> +                qos=2,
Add it to constructor with defualt value 2

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/wolk_connect.py
> +                # TODO: "FIRMWARE_UPDATE_CHECK_TIME"
implement it

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/wolk_connect.py
> +            # NOTE: "FIRMWARE_UPDATE_CHECK_TIME"
implement

2021-09-10 13:32 UTC, srdjastankovic commented on wolk/wolkabout_protocol_message_deserializer.py
> +    TIME = "time"
You have this parameters in two moduels defined. Export it into separated module.

2021-09-16 07:43 UTC, srdjastankovic commented
**REMINDER**:
Manifests have to be included in platform release. Communicate with Marko about it.

2021-09-16 08:02 UTC, srdjastankovic commented
FFS to push

2021-09-16 09:46 UTC, srdjastankovic commented
FU report error:
```
Installing firmware from path: /home/sstankovic/git/WolkConnect-Python/files/main.py
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable
```

2021-09-16 09:48 UTC, srdjastankovic commented
FU leave device at state `DEVICE_MANAGEMENT_INSTALLING`.
Env int4

2021-09-17 13:54 UTC, djesic commented
Closing pull request to maintain the `development` branch strategy, as discussed.
https://github.com/Wolkabout/WolkConnect-Python/releases/tag/v5.0.0-prerelease2

2021-09-17 13:54 UTC, closed without merging